server:
  port: 8082

spring:
  application:
    name: asset-service
  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
