server:
  port: 8080

spring:
  application:
    name: auth-service
  profiles:
    default: local

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:3000/oauth2/code/google
            scope:
              - profile
              - email


eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  access-token:
    private-key-path: classpath:private-key
