server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service-route
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=2

eureka:
  client:
    enabled: true # 유레카 클라이언트 활성화
    service-url:
      defaultZone: http://localhost:8761/eureka/
