server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: block-internal-api-route
              uri: no://op
              predicates:
                - Path=/api/users/internal/**, /api/assets/internal/**
              filters:
                - SetStatus=404
              order: -1

            # auth-service
            - id: auth-service-route
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=2

            # user-service
            - id: user-service-route
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=2
                - Authentication

            # asset-service
            - id: asset-service-route
              uri: lb://asset-service
              predicates:
                - Path=/api/assets/**
              filters:
                - StripPrefix=2
                - Authentication

            # activity-service
            - id: activity-service-route
              uri: lb://activity-service
              predicates:
                - Path=/api/activities/**
              filters:
                - StripPrefix=2
                - Authentication

            # market-data-service
            - id: market-data-service-route
              uri: lb://market-data-service
              predicates:
                - Path=/api/market-data/**
              filters:
                - StripPrefix=2
                - Authentication

            # strategy-service
            - id: strategy-service-route
              uri: lb://strategy-service
              predicates:
                - Path=/api/strategies/**
              filters:
                - StripPrefix=2
                - Authentication

eureka:
  client:
    enabled: true # 유레카 클라이언트 활성화
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  access-token:
    public-key-path: classpath:public-key
