spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/market_data
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create

  kafka:
    consumer:
      bootstrap-servers: localhost:9092

  data:
    redis:
      host: localhost
      port: 6379
