server:
  port: 8084

spring:
  application:
    name: market-data-service
  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

  kafka:
    consumer:
      group-id: market-data-service-group

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

kis:
  url: https://openapi.koreainvestment.com:9443
  ws-url: ws://ops.koreainvestment.com:21000
  app-key: ${KIS_APP_KEY}
  app-secret: ${KIS_APP_SECRET}
