spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/activity
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
